version: '2'

services:
  app:
    build: .
    restart: always
    ports:
      - "80:80"
    links:
      - redis
  redis:
    image: redis
  monitor:
    build: .
    ports:
     - "5555:5555"
    command:  celery -A app.app.celery_app flower --address=0.0.0.0 --port=5555
    depends_on:
      - redis